(()=>{
const UNITS=[
{id:"karabudun",name:"Karabudun",attack:20,infDef:30,cavDef:15,type:"infantry",image:"assets/karabudun.png"},
{id:"kemankes",name:"Kemankeş",attack:25,infDef:100,cavDef:30,type:"archer",image:"assets/kemankes.png"},
{id:"tapukci",name:"Tapukçı",attack:10,infDef:20,cavDef:150,type:"infantry",image:"assets/tapukci.png"},
{id:"mavi-kurt",name:"Mavi Kurt",attack:100,infDef:80,cavDef:40,type:"infantry",image:"assets/mavi-kurt.png"},
{id:"muhafiz",name:"Muhafız",attack:40,infDef:140,cavDef:50,type:"cavalry",image:"assets/muhafiz.png"},
{id:"mavi-atli",name:"Mavi Atlı",attack:110,infDef:50,cavDef:50,type:"cavalry",image:"assets/mavi-atli.png"},
{id:"kursad",name:"Kürşad",attack:150,infDef:110,cavDef:110,type:"cavalry",image:"assets/kursad.png"},
{id:"mancinik",name:"Mancınık",attack:90,infDef:45,cavDef:130,type:"siege",image:"assets/mancinik.png"},
{id:"topcu",name:"Topçu",attack:160,infDef:55,cavDef:150,type:"siege",image:"assets/topcu.png"},
{id:"casus",name:"Casus",attack:10,infDef:10,cavDef:10,type:"scout",image:"assets/casus.png"}
];
const $=id=>document.getElementById(id),atkHost=$("attackerUnits"),defHost=$("defenderUnits");if(!atkHost||!defHost)return;
const clamp=(v,min=0,max=999999999)=>{const n=parseInt(String(v).replace(/[^0-9-]/g,""),10);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):min};
function card(u,side){const a=document.createElement("article");a.className="unit-card";const img=document.createElement("img");img.src=u.image;img.alt=u.name;img.loading="lazy";const n=document.createElement("div");n.className="unit-name";n.textContent=u.name;const input=document.createElement("input");input.type="number";input.min="0";input.step="1";input.value="0";input.inputMode="numeric";input.dataset.side=side;input.dataset.unit=u.id;input.setAttribute("aria-label",(side==="attacker"?"Saldıran ":"Savunan ")+u.name+" adedi");input.addEventListener("change",()=>input.value=clamp(input.value));a.append(img,n,input);return a}
UNITS.forEach(u=>{atkHost.appendChild(card(u,"attacker"));defHost.appendChild(card(u,"defender"))});
function army(side){const c={};let total=0;document.querySelectorAll('input[data-side="'+side+'"]').forEach(i=>{const v=clamp(i.value);i.value=v;c[i.dataset.unit]=v;total+=v});return{counts:c,total}}
function cavRatio(a){if(!a.total)return 0;let c=0;UNITS.forEach(u=>{if(u.type==="cavalry")c+=a.counts[u.id]||0});return c/a.total}
function attackPower(a){let p=0;UNITS.forEach(u=>p+=(a.counts[u.id]||0)*u.attack);const k=a.counts.kemankes||0;const foot=(a.counts.karabudun||0)+(a.counts.tapukci||0)+(a.counts["mavi-kurt"]||0);p+=Math.min(k,foot)*25;return p}
function defensePower(d,a,wall){const r=cavRatio(a);let p=0;UNITS.forEach(u=>{const e=u.infDef*(1-r)+u.cavDef*r;p+=(d.counts[u.id]||0)*e});let nb=0;if(a.total&&d.total>a.total)nb=Math.min(.20,((d.total/a.total)-1)*.10);return p*(1+.04*wall)*(1+nb)}
function typeMult(u,side){if(side==="attacker"){if(u.type==="siege")return 1.5;if(u.id==="kemankes")return 1.15;if(u.type==="cavalry")return .85;return 1}if(u.type==="siege")return 1.25;if(u.type==="cavalry")return .9;return 1}
function distribute(a,e,totalLoss,side){const out={};UNITS.forEach(u=>out[u.id]=0);if(totalLoss<=0||a.total<=0)return out;if(totalLoss>=a.total){UNITS.forEach(u=>out[u.id]=a.counts[u.id]||0);return out}const r=cavRatio(e);const rows=UNITS.map(u=>{const count=a.counts[u.id]||0;const def=Math.max(1,u.infDef*(1-r)+u.cavDef*r);return{id:u.id,count,weight:count*(typeMult(u,side)/def)}});const tw=rows.reduce((s,x)=>s+x.weight,0);let assigned=0;const rem=[];rows.forEach(x=>{const exact=totalLoss*(x.weight/tw);const base=Math.min(x.count,Math.floor(exact));out[x.id]=base;assigned+=base;rem.push({id:x.id,cap:x.count,r:exact-Math.floor(exact)})});rem.sort((a,b)=>b.r-a.r);while(assigned<totalLoss){let moved=false;for(const x of rem){if(assigned>=totalLoss)break;if(out[x.id]<x.cap){out[x.id]++;assigned++;moved=true}}if(!moved)break}return out}
const fmt=n=>new Intl.NumberFormat("tr-TR").format(n);
function render(id,a,l){const h=$(id);h.innerHTML="";const active=UNITS.filter(u=>(a.counts[u.id]||0)>0);if(!active.length){const e=document.createElement("div");e.className="result-row empty";e.textContent="Asker girilmedi.";h.appendChild(e);return}const hd=document.createElement("div");hd.className="result-row header";["Birim","Başlangıç","Ölen","Kalan"].forEach(t=>{const s=document.createElement("span");s.textContent=t;hd.appendChild(s)});h.appendChild(hd);active.forEach(u=>{const start=a.counts[u.id]||0,dead=l[u.id]||0,row=document.createElement("div");row.className="result-row";[u.name,fmt(start),fmt(dead),fmt(start-dead)].forEach(t=>{const s=document.createElement("span");s.textContent=t;row.appendChild(s)});h.appendChild(row)})}
$("simulateButton").addEventListener("click",()=>{const a=army("attacker"),d=army("defender"),wall=clamp($("wallLevel").value,0,20);$("wallLevel").value=wall;if(!a.total||!d.total){$("validationMessage").textContent="İki tarafa da en az bir asker girmen gerekiyor.";$("winnerText").textContent="İki tarafa da en az bir asker gir.";render("attackerResults",a,{});render("defenderResults",d,{});return}$("validationMessage").textContent="";const ap=attackPower(a),dp=defensePower(d,a,wall),aw=ap>dp,strong=Math.max(ap,dp),weak=Math.min(ap,dp);const base=(weak**1.2)/((weak**1.2)+(strong**1.2));const winRate=Math.min(.90,Math.max(0,base*1.8));const al=aw?Math.round(a.total*winRate):a.total,dl=aw?d.total:Math.round(d.total*winRate);$("winnerText").textContent=aw?"SALDIRAN KAZANDI":"SAVUNAN KAZANDI";render("attackerResults",a,distribute(a,d,al,"attacker"));render("defenderResults",d,distribute(d,a,dl,"defender"));$("results").scrollIntoView({behavior:"smooth",block:"start"})});
render("attackerResults",{counts:{},total:0},{});render("defenderResults",{counts:{},total:0},{});
})();